### ISSUE TITLE
Baseline Imec support 

### ISSUE THREAD

**Issue by davidackerman** [JaneliaSciComp/spoke#1]
Baseline support for handling data from imec probes. No increase in data throughput, so processing pipeline should be applied to a channel subset (128 or less), i.e. equivalent to Whisper data processing rates.

SpikeGLX MATLAB interface functions used by Spoke:

- SpikeGL
- Close
- FetchNI
- GetParams
- GetSaveChansNI
- GetScanCountNI
- IsRunning

**Comment by vijayiyer05** [comment]
Baseline support for Imec Phase3a & Phase3b as of 1413e40cc36b7ff522a572d2edca1836acbcd508
