### ISSUE TITLE
Spikes accumulated faster than they should given refresh rate

### ISSUE THREAD

**Issue by davidackerman** [JaneliaSciComp/spoke#14]
Here , there are two sets of accumulations within 3 seconds, even though the refresh rate is 3.3 seconds.
![image](https://user-images.githubusercontent.com/19193291/49966013-d0959100-feec-11e8-8645-a861ca6ec738.png)

**Comment by vijayiyer05** [comment]
Instrumenting the refresh period revealed it's shorter than expected (e.g. 2.7s instead of expected 3.3s). This accounts for the unexpected behavior. Need to investigate this significant time scaling error with SpikeGLX team, i.e. is it related to the NI scan rate?

**Comment by davidackerman** [comment]
This was due to the fact that the niSampRate was set incorrectly in SpikeGLX for this specific whipser probe (default 25000 vs measured value of 20833.439655,)
