### ISSUE TITLE
Recent MATLAB compatibility (beyond R2016a)

### ISSUE THREAD

**Issue by vijayiyer05** [JaneliaSciComp/spoke#2]

**Comment by davidackerman** [comment]
Issue starts in either 2016b or 2017a.

**Comment by vijayiyer05** [comment]
Reproduced w/o SpikeGLX/hardware on branch https://github.com/JaneliaSciComp/spoke/tree/feature_Issue0002

**Comment by vijayiyer05** [comment]
Fixed at 1186b37df0fff343424c842dc8add9b9a41aed61
