### ISSUE TITLE
Filter being applied to non-neural channels

### ISSUE THREAD

**Issue by davidackerman** [JaneliaSciComp/spoke#3]
This filtering is affecting stimulus detection on non-neural channels, on at least some rigs
Branch: https://github.com/JaneliaSciComp/spoke/tree/bugfix_FilterNonNeural

**Comment by davidackerman** [comment]
https://github.com/JaneliaSciComp/spoke/tree/bugfix_FilterNonNeural

**Comment by vijayiyer05** [comment]
Now get error w/ filter applied when sglChanSaves is a subset of available channels
We need to limit processing to the subset, but specifically the neural subset

**Comment by davidackerman** [comment]
Fixed at a75a1fbb188679996668e644e0a8abb818003fa3
