### ISSUE TITLE
Live changes of waveformsPerPlot produce errors and/or don't get applied

### ISSUE THREAD

**Issue by vijayiyer05** [JaneliaSciComp/spoke#32]
* Reductions in value sometimes gives "cell array index" error
* Switching from 1 to 2 sometimes has no effect

**Comment by davidackerman** [comment]
Appears addressed as of 8672a5d01544147b6b689ca8a5d5fc1c9edc1f72. We did seem to observe an issue earlier with live _increases_ in waveformsPerPlot, but have not been able to reproduce.
